# Generated by Django 5.1.4 on 2025-01-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='amount',
            new_name='price',
        ),
    ]
