# Generated by Django 5.1.4 on 2025-01-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_payment_checkout_id_alter_contactquery_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageimage',
            name='user',
        ),
    ]
