# Generated by Django 5.1.4 on 2025-01-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_remove_packageimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checkout_id',
            field=models.CharField(default='stripe', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=150),
        ),
    ]
