# Generated by Django 5.1.4 on 2025-02-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtour',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
