# Generated by Django 5.1.4 on 2025-02-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_alter_bookingtour_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtour',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('cancel', 'Cancel'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
